In [31]:
import pandas as pd
import sqlite3

In [32]:
df = pd.read_csv("enhanced_zomato_dataset_clean.csv")

In [33]:
df.head()

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining_Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,...,Is_Bestseller,Restaurant_Popularity,Avg_Rating_Restaurant,Avg_Price_Restaurant,Avg_Rating_Cuisine,Avg_Price_Cuisine,Avg_Rating_City,Avg_Price_City,Is_Highly_Rated,Is_Expensive
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NONE,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0

In [34]:
conn = sqlite3.connect("zomato.db")

In [35]:
df.to_sql(
    "zomato",
    conn,
    if_exists="replace",
    index=False
)

123657

In [36]:
pd.read_sql("SELECT * FROM zomato LIMIT 5;", conn)

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining_Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,...,Is_Bestseller,Restaurant_Popularity,Avg_Rating_Restaurant,Avg_Price_Restaurant,Avg_Rating_Cuisine,Avg_Price_Cuisine,Avg_Rating_City,Avg_Price_City,Is_Highly_Rated,Is_Expensive
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NONE,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,...,1,46,4.05,171.347826,3.81868,255.954894,3.939031,245.130482,1,0

In [37]:
pd.read_sql("""
SELECT Restaurant_Name, City
FROM zomato;
""", conn)

              Restaurant_Name        City
0                  Doner King   Hyderabad
1                  Doner King   Hyderabad
2                  Doner King   Hyderabad
3                  Doner King   Hyderabad
4                  Doner King   Hyderabad
...                       ...         ...
123652  Ariena Boutique Hotel      Raipur
123653  Ariena Boutique Hotel      Raipur
123654  Ariena Boutique Hotel      Raipur
123655  Ariena Boutique Hotel      Raipur
123656  Ariena Boutique Hotel      Raipur

[123657 rows x 2 columns]

In [38]:
df.columns.tolist()

['Restaurant_Name',
 'Dining_Rating',
 'Delivery_Rating',
 'Dining_Votes',
 'Delivery_Votes',
 'Cuisine',
 'Place_Name',
 'City',
 'Item_Name',
 'Best_Seller',
 'Votes',
 'Prices',
 'Average_Rating',
 'Total_Votes',
 'Price_per_Vote',
 'Log_Price',
 'Is_Bestseller',
 'Restaurant_Popularity',
 'Avg_Rating_Restaurant',
 'Avg_Price_Restaurant',
 'Avg_Rating_Cuisine',
 'Avg_Price_Cuisine',
 'Avg_Rating_City',
 'Avg_Price_City',
 'Is_Highly_Rated',
 'Is_Expensive']

In [39]:
pd.read_sql("""
SELECT *
FROM zomato
WHERE Average_Rating > 4.5;
""", conn)

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining_Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,...,Is_Bestseller,Restaurant_Popularity,Avg_Rating_Restaurant,Avg_Price_Restaurant,Avg_Rating_Cuisine,Avg_Price_Cuisine,Avg_Rating_City,Avg_Price_City,Is_Highly_Rated,Is_Expensive
0,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Tender Coconut Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
1,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Mango (Medium Fat) Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
2,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Chocobite Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
3,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Roasted Almond Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
4,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Kesar Pista Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
5,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Coffee Walnut Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
6,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Orange Pistachio (Medium Fat) Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
7,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Chickoo Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
8,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Butterscotch Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
9,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Make your Own Combo,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,1
10,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Choco Almond Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
11,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Anjeer Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
12,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Sitaphal Ice Cream,MUST TRY,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
13,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,"Mango (Medium Fat Ice Cream, No Added Sugar)",NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
14,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,"Anjeer (Medium Fat Ice Cream, No Added Sugar)",NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
15,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Sitaphal Ice Cream,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
16,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Mango (Medium Fat) Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
17,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Lychee Ice Cream,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
18,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Musk Mango (Medium Fat) Ice Cream,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
19,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Fig and Honey (Medium Fat) Ice Cream,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
20,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Butterscotch Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
21,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,PSG Ice Cream,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
22,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Orange Pistachio (Medium Fat) Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
23,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Tender Coconut Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
24,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Roasted Almond Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
25,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Chocobite Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
26,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Choco Almond Ice Cream,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
27,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Coffee Walnut Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
28,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Kaju Kismis Ice Cream,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
29,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Choco cream Ice Cream,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
30,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Anjeer Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
31,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Chickoo Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
32,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Malai Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
33,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Kesar Pista Ice Cream,BESTSELLER,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,0
34,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Signature Mini Pack Dry Fruit Combo,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,1
35,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Signature Mini Pack Chocolate Combo,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,1
36,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Signature Mini Pack Fruit Combo,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,1
37,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Make your Own Combo,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,1
38,Natural Ice Cream,4.8,4.5,0,0,Beverages,Connaught Place,New Delhi,Best of Three Worlds Mini Pack Combo,NONE,...,1,105,4.40207,137.704095,3.928624,254.565364,3.943863,235.347676,1,1

In [40]:
pd.read_sql("""
SELECT Restaurant_Name, Average_Rating
FROM zomato
ORDER BY Average_Rating DESC;
""", conn)

             Restaurant_Name  Average_Rating
0          Natural Ice Cream            4.65
1          Natural Ice Cream            4.65
2          Natural Ice Cream            4.65
3          Natural Ice Cream            4.65
4          Natural Ice Cream            4.65
...                      ...             ...
123652  Manchatti Restaurant            3.00
123653  Manchatti Restaurant            3.00
123654  Manchatti Restaurant            3.00
123655  Manchatti Restaurant            3.00
123656  Manchatti Restaurant            3.00

[123657 rows x 2 columns]

In [41]:
pd.read_sql("""
SELECT Restaurant_Name, Average_Rating
FROM zomato
ORDER BY Average_Rating DESC
LIMIT 10;
""", conn)

     Restaurant_Name  Average_Rating
0  Natural Ice Cream            4.65
1  Natural Ice Cream            4.65
2  Natural Ice Cream            4.65
3  Natural Ice Cream            4.65
4  Natural Ice Cream            4.65
5  Natural Ice Cream            4.65
6  Natural Ice Cream            4.65
7  Natural Ice Cream            4.65
8  Natural Ice Cream            4.65
9  Natural Ice Cream            4.65

In [42]:
pd.read_sql("""
SELECT City, COUNT(*) AS Total_Restaurants
FROM zomato
GROUP BY City;
""", conn)

             City  Total_Restaurants
0       Ahmedabad              10178
1       Banaswadi                 97
2       Bangalore              12040
3         Chennai              13100
4             Goa               2360
5       Hyderabad              15613
6          Jaipur              14438
7           Kochi               7759
8         Kolkata               8662
9         Lucknow               6455
10   Magrath Road                 54
11   Malleshwaram                 43
12         Mumbai              13535
13      New Delhi               3490
14           Pune               8067
15         Raipur               7700
16         Ulsoor                 66

In [43]:
pd.read_sql("""
SELECT City, AVG(Average_Rating) AS Avg_Rating
FROM zomato
GROUP BY City;
""", conn)

             City  Avg_Rating
0       Ahmedabad    3.851588
1       Banaswadi    3.750000
2       Bangalore    3.875295
3         Chennai    3.889413
4             Goa    3.898374
5       Hyderabad    3.939031
6          Jaipur    3.892180
7           Kochi    3.869203
8         Kolkata    3.907014
9         Lucknow    3.909544
10   Magrath Road    3.600000
11   Malleshwaram    4.000000
12         Mumbai    3.886635
13      New Delhi    3.943863
14           Pune    3.882244
15         Raipur    3.880503
16         Ulsoor    3.911132